name: CI

on:
  push:
    branches:
      - desenvolvimento
  pull_request:
    branches:
      - desenvolvimento
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  guard:
    name: Fast Guard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ci-guard (fast)
        run: |
          if [ -f scripts/ci-guard.sh ]; then
            chmod +x scripts/ci-guard.sh
            bash scripts/ci-guard.sh
          else
            echo "scripts/ci-guard.sh não encontrado (ok)."
          fi

  audit:
    name: Deep Repo Audit
    runs-on: ubuntu-latest
    needs: guard
    steps:
      - uses: actions/checkout@v3

      - name: Run repo-audit (deep checks)
        run: |
          if [ -f scripts/repo-audit.sh ]; then
            chmod +x scripts/repo-audit.sh
            bash scripts/repo-audit.sh
          else
            echo "scripts/repo-audit.sh não encontrado (ok, auditor desligado)."
          fi

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    needs: audit
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (lockfile opcional)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i --no-audit --no-fund
          fi
      - name: TypeScript noEmit
        run: npx tsc -noEmit
