name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run guard script
        run: bash scripts/ci-guard.sh