name: CI

on:
  push:
    branches:
      - desenvolvimento
  pull_request:
    branches:
      - desenvolvimento
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  guard:
    name: Fast Guard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Torna exec. se existir; não falha se não existir
      - name: Ensure scripts executable
        run: |
          chmod +x scripts/ci-guard.sh || true
          chmod +x scripts/repo-audit.sh || true

      - name: Run ci-guard (fast)
        run: |
          if [ -f scripts/ci-guard.sh ]; then
            bash scripts/ci-guard.sh
          else
            echo "scripts/ci-guard.sh não encontrado (ok, mas recomendo subir)."
          fi

  audit:
    name: Deep Repo Audit
    runs-on: ubuntu-latest
    needs: guard
    steps:
      - uses: actions/checkout@v3

      - name: Run repo-audit (deep checks)
        run: |
          if [ -f scripts/repo-audit.sh ]; then
            bash scripts/repo-audit.sh
          else
            echo "❌ scripts/repo-audit.sh ausente. Crie-o em scripts/repo-audit.sh (conteúdo no README/Chat)."
            exit 1
          fi

  typecheck:
    name: TypeScript Check (adaptive)
    runs-on: ubuntu-latest
    needs: audit
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # Sem 'cache' para não exigir lockfile

      - name: Enable corepack (pnpm/yarn)
        run: corepack enable

      - name: Install dependencies (adaptive)
        shell: bash
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "Detected pnpm"
            pnpm i --frozen-lockfile
          elif [ -f yarn.lock ]; then
            echo "Detected yarn"
            yarn install --frozen-lockfile
          elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            echo "Detected npm with lockfile"
            npm ci
          else
            echo "No lockfile found - using npm install"
            npm i --no-audit --no-fund
          fi

      - name: TypeScript noEmit
        run: npx tsc -noEmit
