name: hourly-purge

on:
  schedule:
    - cron: "0 * * * *"   # a cada hora (UTC)
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: No-op purge placeholder
        run: echo "Executando tarefa horária de limpeza (configure aqui seus scripts)."
