name: Generate package-lock.json

on:
  workflow_dispatch:
  push:
    branches: [ desenvolvimento ]
    paths:
      - 'package.json'

permissions:
  contents: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate lockfile (no install)
        run: npm install --package-lock-only

      - name: Commit & push lockfile if changed
        run: |
          if git status --porcelain | grep -q "package-lock.json"; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore(ci): generate package-lock.json"
            git push
          else
            echo "package-lock.json is up to date. Nothing to commit."
          fi
