name: lockfile-gen

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"   # toda segunda 06:00 UTC

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm cache clean --force
      - run: npm i --package-lock-only
      - name: Commit lockfile changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git add package-lock.json
            git commit -m "chore: regenerate lockfile"
            git push
          else
            echo "Sem mudanças no lockfile."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
